version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
